### ISSUE TITLE
unexpected Error when add the storybook-addon-module-mock

### ISSUE THREAD

**Issue by FoushWare** [ReactLibraries/storybook-addon-module-mock#11]
main.ts file 
```
import type { StorybookConfig } from "@storybook/nextjs";

const config: StorybookConfig = {
  stories: ["../stories/**/*.mdx", "../stories/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/addon-coverage",
    "storybook-addon-module-mock",
    "@storybook/addon-mdx-gfm",
  ],
  framework: {
    name: "@storybook/nextjs",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
  staticDirs: ["../public/"],
  features: {
    storyStoreV7: true,
  },
  typescript: {
    reactDocgen: "react-docgen",
  },
};
export default config;

```
package.json 

```
  "dependencies": {
    "@dnd-kit/core": "^6.0.8",
    "@dnd-kit/sortable": "^7.0.2",
    "@flyyer/use-googlefonts": "^0.4.2",
    "@formatjs/intl-numberformat": "^6.2.3",
    "@react-hook/window-scroll": "^1.3.0",
    "@react-oauth/google": "^0.11.0",
    "@redux-devtools/extension": "^3.2.5",
    "@sentry/browser": "^7.57.0",
    "@sentry/node": "^7.57.0",
    "@sentry/webpack-plugin": "^2.4.0",
    "@storybook/addon-console": "^2.0.0",
    "@storybook/jest": "^0.2.3",
    "@tabler/icons": "^1.92.0",
    "axios": "^0.21.1",
    "cacheable-response": "^2.1.9",
    "classnames": "^2.3.1",
    "cors": "^2.8.5",
    "cross-env": "^7.0.3",
    "d3-scale": "^3.3.0",
    "date-fns": "^2.23.0",
    "dayjs": "^1.10.4",
    "dom-to-image": "^2.6.0",
    "eslint-config-next": "^13.4.9",
    "global": "^4.4.0",
    "hex-to-css-filter": "^5.4.0",
    "hex-to-rgba": "^2.0.1",
    "html2pdf.js": "^0.10.1",
    "i18n-iso-countries": "^7.6.0",
    "intl-pluralrules": "^1.2.2",
    "jsonwebtoken": "^9.0.0",
    "keyv": "^4.0.3",
    "lodash": "^4.17.21",
    "next": "^13.4.9",
    "next-plausible": "^3.11.1",
    "next-redux-wrapper": "^6.0.2",
    "next-seo": "^6.0.0",
    "next-translate": "^1.0.4",
    "nextjs-progressbar": "^0.0.16",
    "nookies": "^2.5.2",
    "qrcode.react": "^3.1.0",
    "react": "^18.2.0",
    "react-animate-height": "^2.0.23",
    "react-bottom-scroll-listener": "^5.0.0",
    "react-collapse": "^5.1.0",
    "react-color": "^2.19.3",
    "react-content-loader": "^6.0.2",
    "react-cropper": "^2.1.8",
    "react-custom-scrollbars-2": "^4.5.0",
    "react-date-range": "^1.3.0",
    "react-device-detect": "^2.2.3",
    "react-dom": "^18.2.0",
    "react-facebook-pixel": "^1.0.4",
    "react-flatpickr": "^3.10.13",
    "react-ga4": "^2.1.0",
    "react-google-recaptcha": "^2.1.0",
    "react-gtm-module": "^2.0.11",
    "react-helmet": "^6.1.0",
    "react-hook-form": "^7.45.1",
    "react-image-crop": "^8.6.9",
    "react-intersection-observer": "^8.31.0",
    "react-linkedin-insight": "^0.1.3",
    "react-loader-spinner": "^5.3.4",
    "react-number-format": "^4.6.3",
    "react-password-checklist": "^1.4.3",
    "react-player": "^2.12.0",
    "react-plx": "^1.3.17",
    "react-redux": "^7.2.2",
    "react-select": "^5.7.3",
    "react-select-country-list": "^2.2.3",
    "react-share": "^4.4.0",
    "react-simple-maps": "^3.0.0",
    "react-slick": "^0.29.0",
    "react-svg": "^14.0.1",
    "react-svg-to-image": "^3.0.0",
    "react-toastify": "^9.1.3",
    "react-tooltip": "^4.2.21",
    "react-transition-group": "^4.4.1",
    "react-use": "^17.4.0",
    "react-verification-input": "^3.3.0",
    "react-virtualized-auto-sizer": "^1.0.5",
    "react-web-share": "^1.1.6",
    "react-window": "^1.8.7",
    "recharts": "^2.7.2",
    "redux": "^4.0.5",
    "rodal": "^2.0.1",
    "slick-carousel": "^1.8.1",
    "storybook-addon-module-mock": "^1.1.1",
    "styled-bootstrap-grid": "^3.1.0",
    "styled-components": "^5.2.1",
    "styled-normalize": "^8.0.7",
    "stylis-rtlcss": "^2.1.1",
    "swiper": "^10.3.0",
    "swr": "^2.2.0",
    "url-parse": "^1.5.1",
    "use-image": "^1.1.1",
    "uuid": "^8.3.2",
    "whatwg-fetch": "^3.6.2"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.0.1",
    "@commitlint/lint": "^17.6.5",
    "@dwmt/commitlint-config-jira-type": "^2.0.0",
    "@dwmt/commitlint-plugin-jira-type": "^2.0.0",
    "@next/bundle-analyzer": "^10.2.3",
    "@storybook/addon-coverage": "^0.0.9",
    "@storybook/addon-essentials": "^7.5.1",
    "@storybook/addon-interactions": "^7.5.1",
    "@storybook/addon-links": "^7.5.1",
    "@storybook/addon-mdx-gfm": "^7.5.1",
    "@storybook/addon-onboarding": "^1.0.8",
    "@storybook/blocks": "^7.5.1",
    "@storybook/nextjs": "^7.5.1",
    "@storybook/react": "^7.5.1",
    "@storybook/test-runner": "^0.13.0",
    "@storybook/testing-library": "^0.2.2",
    "@testing-library/dom": "^9.3.1",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/d3-scale": "^3.3.2",
    "@types/express": "^4.17.11",
    "@types/facebook-js-sdk": "^3.3.2",
    "@types/jest": "^29.5.2",
    "@types/lodash": "^4.14.168",
    "@types/react": "^18.2.12",
    "@types/react-color": "^3.0.4",
    "@types/react-dom": "^18.2.5",
    "@types/react-redux": "^7.1.16",
    "@types/react-simple-maps": "^3.0.0",
    "@types/react-slick": "^0.23.4",
    "@types/react-test-renderer": "^18.0.0",
    "@types/react-transition-group": "^4.4.1",
    "@types/react-virtualized-auto-sizer": "^1.0.0",
    "@types/styled-components": "^5.1.9",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "eslint-import-resolver-typescript": "^2.5.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-storybook": "^0.6.15",
    "express": "^4.17.1",
    "husky": "^5.1.1",
    "jest": "^29.5.0",
    "jest-environment-jsdom": "^29.5.0",
    "jest-styled-components": "^7.1.1",
    "lint-staged": "^10.5.4",
    "msw": "^2.0.0",
    "next-sitemap": "^4.1.3",
    "nodemon": "^2.0.7",
    "prettier": "^2.5.1",
    "react-test-renderer": "^18.2.0",
    "storybook": "^7.5.1",
    "ts-jest": "^29.1.0",
    "ts-node": "^9.1.1",
    "typescript": "^5.0.4",
    "webpack": "^5.88.1"
  },

```

The Error : 
```
Cannot read properties of undefined (reading 'attrs')
TypeError: Cannot read properties of undefined (reading 'attrs')
    at ./node_modules/styled-bootstrap-grid/dist/components/Container/Container.js (http://localhost:6006/vendors-node_modules_babel_runtime_helpers_esm_asyncToGenerator_js-node_modules_babel_runtime-aff414.iframe.bundle.js:119507:46)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:360:21)
    at ./node_modules/styled-bootstrap-grid/dist/components/Container/index.js (http://localhost:6006/vendors-node_modules_babel_runtime_helpers_esm_asyncToGenerator_js-node_modules_babel_runtime-aff414.iframe.bundle.js:119570:41)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:360:21)
    at ./node_modules/styled-bootstrap-grid/dist/index.js (http://localhost:6006/vendors-node_modules_babel_runtime_helpers_esm_asyncToGenerator_js-node_modules_babel_runtime-aff414.iframe.bundle.js:120069:41)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:360:21)
    at ./.storybook/preview.tsx (http://localhost:6006/main.iframe.bundle.js:41:79)
```

**Comment by FoushWare** [comment]
I think The error message that i am  seeing is caused by a conflict between styled-bootstrap-grid and storybook-addon-module-mock. styled-bootstrap-grid uses a feature of React called "forward refs" to pass refs to its child components. storybook-addon-module-mock also uses forward refs, but it does so in a way that is incompatible with styled-bootstrap-grid
